version: "3.9"

services:
  ret2win32:
    build:
      context: ./ret2win
      dockerfile: Dockerfile32
    container_name: ret2win32
    ports:
      - "30000:30000"
    networks:
      - net0
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30000,fork,reuseaddr exec:/home/pwnuser/ret2win32"

  ret2win64:
    build:
      context: ./ret2win
      dockerfile: Dockerfile64
    container_name: ret2win64
    ports:
      - "30001:30001"
    networks:
      - net1
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30001,fork,reuseaddr exec:/home/pwnuser/ret2win64"

  ret2shell32:
    build:
      context: ./ret2shell
      dockerfile: Dockerfile32
    container_name: ret2shell32
    ports:
      - "30002:30002"
    networks:
      - net2
    security_opt:
      - seccomp:unconfined
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "env - setarch x86_64 -R socat tcp-l:30002,fork,reuseaddr exec:/home/pwnuser/ret2shell32"

  ret2shell64:
    build:
      context: ./ret2shell
      dockerfile: Dockerfile64
    container_name: ret2shell64
    ports:
      - "30003:30003"
    networks:
      - net3
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30003,fork,reuseaddr exec:/home/pwnuser/ret2shell64"

  ret2func32:
    build:
      context: ./ret2func
      dockerfile: Dockerfile32
    container_name: ret2func32
    ports:
      - "30004:30004"
    networks:
      - net4
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30004,fork,reuseaddr exec:/home/pwnuser/ret2func32"

  ret2func64:
    build:
      context: ./ret2func
      dockerfile: Dockerfile64
    container_name: ret2func64
    ports:
      - "30005:30005"
    networks:
      - net5
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30005,fork,reuseaddr exec:/home/pwnuser/ret2func64"

  ret2libc32:
    build:
      context: ./ret2libc
      dockerfile: Dockerfile32
    container_name: ret2libc32
    ports:
      - "30006:30006"
    networks:
      - net6
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30006,fork,reuseaddr exec:/home/pwnuser/ret2libc32"

  ret2libc64:
    build:
      context: ./ret2libc
      dockerfile: Dockerfile64
    container_name: ret2libc64
    ports:
      - "30007:30007"
    networks:
      - net7
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL
    command: "socat tcp-l:30007,fork,reuseaddr exec:/home/pwnuser/ret2libc64"

networks:
  net0:
  net1:
  net2:
  net3:
  net4:
  net5:
  net6:
  net7:
